const actionTypes = {
  SET_USER: 'SET_USER',
  UPDATE_USER_DETAILS: 'UPDATE_USER_DETAILS',
  UPDATE_PERSONAL_DETAILS: 'UPDATE_PERSONAL_DETAILS',
  RESET_USER: 'RESET_USER',
  TOGGLE_THEME: 'TOGGLE_THEME',
  SET_CLIPBOARD: 'SET_CLIPBOARD',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};

export default actionTypes;
